CREATE TABLE MASTER_USER_ARIFUDIN (
                                      ID RAW(36) DEFAULT SYS_GUID() PRIMARY KEY,
                                      FULL_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE MASTER_ACCOUNT_ARIFUDIN (
                                         ID RAW(36) DEFAULT SYS_GUID() PRIMARY KEY,
                                         USER_ID RAW(36) NOT NULL,
                                         BALANCE DOUBLE PRECISION NOT NULL,
                                         CONSTRAINT FK_USER_ACCOUNT FOREIGN KEY (USER_ID) REFERENCES MASTER_USER_ARIFUDIN(ID)
);

CREATE TABLE CRUD_ARIFUDIN (
                               ID RAW(36) DEFAULT SYS_GUID() PRIMARY KEY,
                               NAME VARCHAR(255) NOT NULL,
                               EMAIL VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE weather_forecast_arifudin (
                                           id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           provinsi VARCHAR2(255),
                                           kotkab VARCHAR2(255),
                                           kecamatan VARCHAR2(255),
                                           desa VARCHAR2(255),
                                           lon NUMBER(10,6),
                                           lat NUMBER(10,6),
                                           datetime TIMESTAMP,
                                           temperature NUMBER(5),
                                           weather_desc VARCHAR2(255),
                                           wind_speed NUMBER(10,2),
                                           humidity NUMBER(5),
                                           image VARCHAR2(512),
                                           adm1 VARCHAR2(255),
                                           adm2 VARCHAR2(255),
                                           adm3 VARCHAR2(255),
                                           adm4 VARCHAR2(255)
);